# SPDX-FileCopyrightText: 2023 Julian-Samuel Gebühr
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---

- block:
    - when: semaphore_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"

    - when: semaphore_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/install.yml"
  tags:
    - setup-all
    - setup-semaphore
    - install-all
    - install-semaphore

- block:
    - when: not semaphore_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/uninstall.yml"
  tags:
    - setup-all
    - setup-semaphore

- block:
    - when: semaphore_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/add_users_auto.yml"
  tags:
    - ensure-semaphore-users-created
    - ensure-users-created

- block:
    - when: semaphore_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/add_user_manual.yml"
  tags:
    - semaphore-add-user
    - semaphore-add-admin
