# SPDX-FileCopyrightText: 2023 Julian-Samuel Gebühr
# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Perform Semaphore installation tasks
  when: semaphore_enabled | bool
  tags:
    - setup-all
    - setup-semaphore
    - install-all
    - install-semaphore
  block:
    - name: Validate Semaphore configuration
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"
    - name: Install Semaphore
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/install.yml"

- name: Perform Semaphore uninstallation tasks
  when: not semaphore_enabled | bool
  tags:
    - setup-all
    - setup-semaphore
  block:
    - name: Uninstall Semaphore
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/uninstall.yml"
