# SPDX-FileCopyrightText: 2023 Julian-Samuel Gebühr
# SPDX-FileCopyrightText: 2024 Slavi Pantaleev
# SPDX-FileCopyrightText: 2025 Suguru Hirahara
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Check existence of Semaphore UI systemd service
  ansible.builtin.stat:
    path: "{{ devture_systemd_docker_base_systemd_path }}/{{ semaphore_identifier }}.service"
  register: semaphore_service_stat

- name: Uninstall Semaphore UI systemd services and files
  when: semaphore_service_stat.stat.exists | bool
  block:
    - name: Ensure Semaphore UI systemd service is stopped
      ansible.builtin.service:
        name: "{{ semaphore_identifier }}"
        state: stopped
        enabled: false
        daemon_reload: true

    - name: Ensure Semaphore UI systemd service does not exist
      ansible.builtin.file:
        path: "{{ devture_systemd_docker_base_systemd_path }}/{{ semaphore_identifier }}.service"
        state: absent

    - name: Ensure Semaphore UI support files do not exist
      ansible.builtin.file:
        path: "{{ semaphore_base_path }}/{{ item }}"
        state: absent
      with_items:
        - env
        - labels
        - passwd

    - name: Ensure Semaphore UI image source files path does not exist
      ansible.builtin.file:
        path: "{{ semaphore_customized_container_src_path }}"
        state: absent

    - name: Ensure Semaphore UI tmp path does not exist
      ansible.builtin.file:
        path: "{{ semaphore_tmp_path }}"
        state: absent

    - name: Ensure Semaphore UI local config path does not exist if empty
      ansible.builtin.command:
        cmd: "rmdir {{ semaphore_config_path }}"
      register: semaphore_config_path_deletion_result
      changed_when: semaphore_config_path_deletion_result.rc == 0

    - name: Ensure Semaphore UI local data path does not exist if empty
      ansible.builtin.command:
        cmd: "rmdir {{ semaphore_data_path }}"
      register: semaphore_data_path_deletion_result
      changed_when: semaphore_data_path_deletion_result.rc == 0

    - name: Ensure Semaphore UI base path does not exist if empty
      ansible.builtin.command:
        cmd: "rmdir {{ semaphore_base_path }}"
      register: semaphore_base_path_deletion_result
      changed_when: semaphore_base_path_deletion_result.rc == 0

    - name: Ensure Semaphore UI container network does not exist via community.docker.docker_network
      when: devture_systemd_docker_base_container_network_creation_method == 'ansible-module'
      community.docker.docker_network:
        name: "{{ semaphore_container_network }}"
        state: absent

    - name: Ensure Semaphore UI container network does not exist via ansible.builtin.command
      when: devture_systemd_docker_base_container_network_creation_method == 'command'
      ansible.builtin.command:
        cmd: >-
          {{ devture_systemd_docker_base_host_command_docker }} network rm
          {{ semaphore_container_network }}
      register: network_deletion_result
      changed_when: semaphore_container_network in network_deletion_result.stdout

- name: Check existence of Semaphore UI local data path
  ansible.builtin.stat:
    path: "{{ semaphore_data_path }}"
  register: semaphore_data_path_stat

# We just want to notify the user. Deleting data is too destructive.
- name: Notify if Semaphore UI local data remains
  when: semaphore_data_path_stat.stat.exists | bool
  ansible.builtin.set_fact:
    devture_playbook_runtime_messages_list: |
      {{
        devture_playbook_runtime_messages_list | default([])
        +
        [
          "Note: As the local Semaphore UI instance has been removed, some old data remains in `" + semaphore_data_path + "`. Feel free to delete it."
        ]
      }}

- name: Check existence of Semaphore UI config path
  ansible.builtin.stat:
    path: "{{ semaphore_config_path }}"
  register: semaphore_config_path_stat

# We just want to notify the user. Deleting data is too destructive.
- name: Notify if Semaphore UI config remains
  when: semaphore_config_path_stat.stat.exists | bool
  ansible.builtin.set_fact:
    devture_playbook_runtime_messages_list: |
      {{
        devture_playbook_runtime_messages_list | default([])
        +
        [
          "Note: As the local Semaphore UI instance has been removed, some config data remains in `" + semaphore_config_path + "`. Feel free to delete it."
        ]
      }}
