# SPDX-FileCopyrightText: 2023 Julian-Samuel Gebühr
# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: (Deprecation) Catch and report renamed settings
  ansible.builtin.fail:
    msg: >-
      Your configuration contains a variable, which now has a different name.
      Please change your configuration to rename the variable (`{{ item.old }}` -> `{{ item.new }}`).
  when: "item.old in vars"
  with_items:
    - { "old": "semaphore_database_host", "new": "semaphore_database_hostname" }
    - { "old": "semaphore_env_path", "new": "<removed>" }
    - { "old": "semaphore_environment_variables_extension", "new": "semaphore_environment_variables_additional_variables" }

- name: Fail if required Semaphore settings not defined
  ansible.builtin.fail:
    msg: >-
      You need to define a required configuration setting (`{{ item }}`).
  when: "vars[item] == ''"
  with_items:
    - semaphore_uid
    - semaphore_gid
    - semaphore_hostname
    - semaphore_admin_password
    - semaphore_admin_name
    - semaphore_admin_email
    - semaphore_access_key_encryption
