# SPDX-FileCopyrightText: 2023 Julian-Samuel Gebühr
# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: (Deprecation) Catch and report renamed settings
  ansible.builtin.fail:
    msg: >-
      Your configuration contains a variable, which now has a different name.
      Please change your configuration to rename the variable (`{{ item.old }}` -> `{{ item.new }}`).
  when: "lookup('ansible.builtin.varnames', ('^' + item.old + '$'), wantlist=True) | length > 0"
  with_items:
    - { "old": "semaphore_database_host", "new": "semaphore_database_hostname" }
    - { "old": "semaphore_env_path", "new": "<removed>" }
    - { "old": "semaphore_dyn_config_path", "new": "<removed>" }
    - { "old": "semaphore_playbook_path", "new": "<removed>" }
    - { "old": "semaphore_container_playbook_path", "new": "<removed>" }
    - { "old": "semaphore_environment_variables_extension", "new": "semaphore_environment_variables_additional_variables" }

- name: Fail if required Semaphore settings not defined
  ansible.builtin.fail:
    msg: >-
      You need to define a required configuration setting (`{{ item }}`).
  when: "lookup('vars', item, default='') | string | length == 0"
  with_items:
    - semaphore_uid
    - semaphore_gid
    - semaphore_hostname
    - semaphore_path_prefix
    - semaphore_container_network
    - semaphore_admin_username
    - semaphore_admin_password
    - semaphore_admin_name
    - semaphore_admin_email
    - semaphore_access_key_encryption

- name: Run if Traefik is enabled
  when: semaphore_container_labels_traefik_enabled | bool
  block:
    - name: Fail if Traefik settings required for Semaphore are not defined
      ansible.builtin.fail:
        msg: >-
          You need to define a required configuration setting (`{{ item }}`).
      when: "lookup('vars', item, default='') | string | length == 0"
      with_items:
        - semaphore_container_labels_traefik_hostname
        - semaphore_container_labels_traefik_path_prefix

    # We ensure it doesn't end with a slash, because we handle both (slash and no-slash).
    # Knowing that `semaphore_container_labels_traefik_path_prefix` does not end with a slash
    # ensures we know how to set these routes up without having to do "does it end with a slash" checks elsewhere.
    - name: Fail if semaphore_container_labels_traefik_path_prefix ends with a slash
      ansible.builtin.fail:
        msg: >-
          semaphore_container_labels_traefik_path_prefix (`{{ semaphore_container_labels_traefik_path_prefix }}`) must either be `/` or not end with a slash (e.g. `/semaphore`).
      when: "semaphore_container_labels_traefik_path_prefix != '/' and semaphore_container_labels_traefik_path_prefix[-1] == '/'"
