# SPDX-FileCopyrightText: 2023 Julian-Samuel Gebühr
# SPDX-FileCopyrightText: 2023 MASH project contributors
# SPDX-FileCopyrightText: 2023 - 2025 Slavi Pantaleev
# SPDX-FileCopyrightText: 2025 Suguru Hirahara
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: (Deprecation) Catch and report renamed settings
  ansible.builtin.fail:
    msg: >-
      Your configuration contains a variable, which now has a different name.
      Please change your configuration to rename the variable (`{{ item.old }}` -> `{{ item.new }}`).
  when: "lookup('ansible.builtin.varnames', ('^' + item.old + '$'), wantlist=True) | length > 0"
  with_items:
    - { "old": "semaphore_env_path", "new": "<removed>" }
    - { "old": "semaphore_dyn_config_path", "new": "<removed>" }
    - { "old": "semaphore_playbook_path", "new": "<removed>" }
    - { "old": "semaphore_container_playbook_path", "new": "<removed>" }
    - { "old": "semaphore_database_dialect", "new": "semaphore_database_type" }
    - { "old": "semaphore_database_username", "new": "<Replace with semaphore_database_mysql_username or semaphore_database_postgres_username>" }
    - { "old": "semaphore_database_password", "new": "<Replace with semaphore_database_mysql_password or semaphore_database_postgres_password>" }
    - { "old": "semaphore_database_port", "new": "<Replace with semaphore_database_postgres_port or semaphore_database_mysql_port>" }
    - { "old": "semaphore_database_host", "new": "<Replace with semaphore_database_postgres_hostname or semaphore_database_mysql_hostname>" }
    - { "old": "semaphore_environment_variables_extension", "new": "semaphore_environment_variables_additional_variables" }

- name: Fail if required Semaphore UI settings not defined
  ansible.builtin.fail:
    msg: >-
      You need to define a required configuration setting (`{{ item }}`).
  when: "lookup('vars', item, default='') | string | length == 0"
  with_items:
    - semaphore_uid
    - semaphore_gid
    - semaphore_hostname
    - semaphore_path_prefix
    - semaphore_container_network
    - semaphore_admin_username
    - semaphore_admin_password
    - semaphore_admin_name
    - semaphore_admin_email
    - semaphore_access_key_encryption

- name: Fail if Semaphore UI database type invalid
  ansible.builtin.fail:
    msg: >-
      semaphore_database_type must be 'mysql', 'postgres' or 'sqlite'
  when: "semaphore_database_type not in ['mysql', 'postgres', 'sqlite']"

- name: Fail if required Semaphore UI + MySQL integration settings not defined
  ansible.builtin.fail:
    msg: >-
      You need to define a required configuration setting (`{{ item }}`) when `semaphore_database_type` is `mysql`
  when: "semaphore_database_type == 'mysql' and lookup('vars', item, default='') | string | length == 0"
  with_items:
    - semaphore_database_mysql_hostname
    - semaphore_database_mysql_password

- name: Fail if required Semaphore UI + Postgres integration settings not defined
  ansible.builtin.fail:
    msg: >-
      You need to define a required configuration setting (`{{ item }}`) when `semaphore_database_type` is `postgres`
  when: "semaphore_database_type == 'postgres' and lookup('vars', item, default='') | string | length == 0"
  with_items:
    - semaphore_database_postgres_hostname
    - semaphore_database_postgres_password

- name: Fail if SMTP settings are missing (and SMTP is enabled by setting host)
  ansible.builtin.fail:
    msg: >-
      You need to define a required configuration setting (`{{ item }}`) to correctly set up email via SMTP.
  when: "semaphore_environment_variables_email_host !='' and lookup('vars', item, default='') | string | length == 0"
  with_items:
    - semaphore_environment_variables_email_port
    - semaphore_environment_variables_email_sender

- name: Run if Traefik is enabled
  when: semaphore_container_labels_traefik_enabled | bool
  block:
    - name: Fail if Traefik settings required for Semaphore UI are not defined
      ansible.builtin.fail:
        msg: >-
          You need to define a required configuration setting (`{{ item }}`).
      when: "lookup('vars', item, default='') | string | length == 0"
      with_items:
        - semaphore_container_labels_traefik_hostname
        - semaphore_container_labels_traefik_path_prefix

    # We ensure it doesn't end with a slash, because we handle both (slash and no-slash).
    # Knowing that `semaphore_container_labels_traefik_path_prefix` does not end with a slash
    # ensures we know how to set these routes up without having to do "does it end with a slash" checks elsewhere.
    - name: Fail if semaphore_container_labels_traefik_path_prefix ends with a slash
      ansible.builtin.fail:
        msg: >-
          semaphore_container_labels_traefik_path_prefix (`{{ semaphore_container_labels_traefik_path_prefix }}`) must either be `/` or not end with a slash (e.g. `/semaphore`).
      when: "semaphore_container_labels_traefik_path_prefix != '/' and semaphore_container_labels_traefik_path_prefix[-1] == '/'"
