# SPDX-FileCopyrightText: 2023 Julian-Samuel Gebühr
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---

- name: Fail if required semaphore settings not defined
  ansible.builtin.fail:
    msg: >-
      You need to define a required configuration setting (`{{ item }}`) for using this role.
  when: "vars[item] == ''"
  with_items:
    - semaphore_uid
    - semaphore_gid
    - semaphore_hostname
    - semaphore_admin_password
    - semaphore_admin_name
    - semaphore_admin_email
    - semaphore_access_key_encryption
