# SPDX-FileCopyrightText: 2026 Suguru Hirahara
# SPDX-FileCopyrightText: 2026 spatterlight
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml
    force: true
driver:
  name: docker
platforms:
  - name: semaphore-${MOLECULE_DISTRO:-ubuntu2604}-default
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-ubuntu2604}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  config_options:
    defaults:
      callback_result_format: yaml
  inventory:
    group_vars:
      all:
        # Helper variables
        semaphore_debug_service_enabled: false

        # Variables for Semaphore UI
        semaphore_uid: 1000
        semaphore_gid: 1000
        semaphore_hostname: localhost
        semaphore_container_labels_traefik_enabled: false
        semaphore_container_http_host_bind_port: 3000
        semaphore_admin_username: username
        semaphore_admin_password: password
        semaphore_admin_name: name
        semaphore_admin_email: example@example.com
        semaphore_access_key_encryption: SZzA3p6dEkpO3MP3w+OI3iUDalRtGX8B93TMmJj/ojk=
  env:
    # Workaround for https://github.com/ansible/molecule/issues/4391
    ANSIBLE_ROLES_PATH: ${MOLECULE_PROJECT_DIRECTORY}/..:/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles:~/.ansible/roles
verifier:
  name: ansible
